sudo: required

language: generic

services:
  - docker
  - xvfb

env:
  global:
    - secure: EeG9leca0EHSpQRUbm4hFVTaXrjzTmNZuSrJ+g+AQw7LBtxF9IE16ffGowuKmk9TFnfyaZxxyy/nAKy7GUKBepz8ZocJNS3QX8112AutoP3wRCt8LrYqnUnaDjDTfUafM85iNHHbiYVJj4DcjFumRlgU/rZRqnrOcfG6eBrylRWRHwXXwE7CgpgMwjioR10PuOIezCGbDcE8MTPH0tqUfcS+7UgkbAD9K7LL4+mH9g3UIcichk3As+vtPFWPylLdv7YTcJpy4bYewBPEvqvvFwwGt3Bv4No670LKVof9QGCsEGLpCUB850PCBMQo1+OxoeW9oUCChitLTQ9sEbVADNxNmRThQ/f+i949vl9NhYgXbXf5i0By9kMRBo66vo4drOpvpZriSkbHT4rsMMWyRZYfZ37KELvGtELNOKs3wHJ2HIQmukQckTJUGs8HJVYO3H1g8npgvaPf/KyyMGofm9bI7qFBlagk8lK92UiGvjdSmk33YvXOMc0pGu+Hp3fUxj1lxiLQtSmHRatM6nXxg9JLg0ywfDi95IoxuTmEvLfl1MNg9ii87Kjne8xf6ACSauYlVNHNkkvJlmvGh0S20OdNYk0vbWiOOOD+QPf5wqd+i4RksJC9kVvCk/TjfFbqgn/0WC3t4X73n5QEZ1QetoJbFl3iE3fGh7BVUhkFMy4=
    - secure: HMt1lfrpXujQWKj16/pX9ZRSoX9WtBo8hJ5DvxI4YWQkdNUmpKCo/Ds6Za4xN3QOgoGuV1XpwxxjaczXnktiMGptq2jccTPxbIIWN99n0xBG2JL2a1nwTpagn1uQdinT+x/XAPE2fOBoAYxaAsAJbgYGOJrtgjOuTPmXIlU/ErOeje4MkMWjLxWArUMzcWx0Em13nrFoeI5fvWp80luJZ8h5wDTUU96vBkPyfDLPk+WtBTbmdH9PFXsnepkTasYDmWQc64EOwlRcGXF+BmW7s9V8Kt9JkCWpyigX3Ls2vIlWs7a9Fae+Dm56ExDzXKE6TlP9fMtM17EimXZ7bxciPTTKBhderUhNNaPugq8w1SPswyfqNtMniUiVkstzdvfbny0vU1RPblQruVqBa2jAyafSdK0Smo/pKYog+Q/ClkUXiLhQ55kXoi7Fsse5q6TLm+PuwoKUzvoTH3Syp0xytuFsZSgmpPK2/VNcZxaLcQfhx7rkABxfLrnPFJaj7IrSLd1d/6cI9JrhTL3e9mMzT4CfpeGltKUXquJP7yRMNqWO4XNnTcht63LoSzDDji9dMvChPiGkC7fxMd2qMSQnIL11lNZymJYUfaD/sK52w5ngMXNAoZ9uGSgZsFn55rXt1UbRJRX4xijnAH8qzt87/aMWqDvOZcIF9UwYNVSP3pA=

before_script:
  - make docker/pull

script:
  - make docker/run/test

deploy:
  provider: script
  script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD && make docker/push
  on:
    branch: develop
