sudo: required

language: generic

services:
  - docker
  - xvfb

before_script:
  - make docker/pull

script:
  - make docker/run/test

deploy:
  provider: script
  script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD && make docker/push
  on:
    branch: develop
