sudo: required

language: generic

services:
  - docker
  - xvfb

env:
  global:
    - secure: ytX/Mh2bsb+VuTH/QbY1dzD+mJzWxdGboDyycxx6LWVgJYYZW4uI4MXnaQrzMuaK4Wk3MVyfKDV4ryjEB1I/r2S6W6neVVrJHUBVPt0+cgPQG9fF6v0Wx+po5/DoQnx/xIaL1emEzwgLmnd7TR0a6XuXhG1GgEs+Su1Yg8P6JRhFU2n56Bl0sonaEIMFc5wtfD2jmymDLyp2Z6dCafcfKHV69fKmiuUc754iTID02jXPNQic3J94vuaUtKFDYdSRf3tu2OH4lSJpVrnTwR1dATZGfWN7Y1HWaU/LJg9SDSyYW57ch7yqWiJOmitzn8Po1f72AFrA09/IKu3/olXLHeqihtkbZoXRoTnm6PP7wOALeoHZ6C6ag4OTQhvuhOHxLd+/nIuuZPqJWGAnNkzBxhf9uqA0B1USLujjTjzP76Z0NDHmQHeV+XOhE1hpfEoXG3cCgFbHWxfrgNzxoUPmzY7VhsHvp3Xowa67vqXq1Cfp4G0Zan9g5RLQrmcgs0qmZ/TU7lj8n6ODQsVOieLRe6ep5c+QgQvuUnctewuYRmXUGw3JwsxC3gS0m+2UqgSGBEEfSN4rijM0cPKwW4B1k9ru66zHPZBrPPmJ9Nq0oTFvUbyZ/jODoTAgj4bt4usHtrvSrtoDAGJKi/sEyVABNWfRc45o4crf/eZDQA8pt/U=
    - secure: eUxaOhpIDgaC+782FXlZMC5ddp6QEVxFgLYAb6k9zhKenaULEuTpbbJ0yJHKzalciqHthMktq2JNguYn8VtVCpni09DJV08X0AR7Icl9VOuo4eYaaqonoQYgyu+whTcpZFbSzZEovOAId+yXnTWR/hKhDjrn5DSS+T6Jw6jNYJuBUECLTb4DRbvYZ5I2bHhymbBqMKk+dVp7qqa4ePxjswlpgCpg7lcPjeqeVUOnr75/Q6ClXMcUUHx/yGw0EzkBb9bF4lit3UHxwkjTCYK01UwtEIPvZ2ToXfKDBMrNOAJnijht4VhGb2CEDoYA7iSy3034QEWvzUsuxvfGtP8+OnmUobncuAzrIZy7eT0yzYIS3H3dBGfaHIhRTUnGNLSN6VekwMWToUJdttSpT5DBz4s51QvPwJOw/bj+FazQJSccYc2oSYDTp1lzI8ZaPEb9wBvVziKBYxqTjArO6Q3wFT8az0PKOWuPxGeY9yXQqWcq30LIyQEl/I51pXBikQnlCWeRTnYjKHLovyfaHGnR+jx7jpBdK0hptSRWfNBR3AyzHEx8i+E/dz1CZi1CO+tbgzJzUtUi8JMvsr6H4b4qHqoM47q5QbCHaw6icdcD9Y5C6+UFbG0CyxqREJIgD9NgJ6N7E4c4YNg+OnL1hDeoYHqUR/cD8Ox7DBQusmS9CPA=

script:
  - make docker/run/test

deploy:
  provider: script
  script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD && make docker/push
  on:
    branch: develop
